### PR TITLE
Fix issue with footnotes forcing rectangular extent for selection

### PR DESCRIPTION
**Pull request by beansrowning**
## Note

I separately encountered the issue in #264. I didn't see the open PR in #265, so my solution is slightly different. Feel free to disregard, or combine. I didn't include unittests here, but they could be provided.

## Proposal

This PR fixes an issue (or undocumented behavior) where specifying >1 `i` or `j` in `footnote()` always forces a rectangular extent to be returned due to matrix subsetting.

For instance, a user may want to specify exact row and column indices:

```r
library(flextable)
library(dplyr)

tab <- iris %>%
  head(10)

#   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#1           5.1         3.5          1.4         0.2  setosa
#2           4.9         3.0          1.4         0.2  setosa
#3           4.7         3.2          1.3         0.2  setosa
#4           4.6         3.1          1.5         0.2  setosa
#5           5.0         3.6          1.4         0.2  setosa
#6           5.4         3.9          1.7         0.4  setosa
#7           4.6         3.4          1.4         0.3  setosa
#8           5.0         3.4          1.5         0.2  setosa
#9           4.4         2.9          1.4         0.2  setosa
#10          4.9         3.1          1.5         0.1  setosa

note <- "This is a test, look at these three observations"
j <- c(3, 1, 1)
i <- c(6, 1, 6)

# Erroneously adds 3,1 even though it wasn't specified
tab %>%
  flextable()
  footnote(i = i, j = j, ref_symbols = "1", value = as_paragraph(note))
```
image

This is due to the `[.chunkset_struct` method, which must return a rectangular extent since it's using matrix-style subsetting. A potential patch could instead treat subsetting cell-wise, with a small performance hit.

After patch:

image

### CODE REVIEW

**Comment by davidgohel** [comment]
Thank you for this, awesome and simple.

Don't worry, I'll add a few tests and document your contribution. 

I will also add you as contributor in the DESCRIPTION file if you don't mind.

**Comment by beansrowning** [comment]
@davidgohel Great! Yes, very happy and humbled to be included. We were developing an internal report when we noticed this issue in review, and I figured others could benefit from the solution.

**Comment by davidgohel** [comment]
Hi @beansrowning, just to let you know ; I changed your code (but not the behavior) and added documentation.

I used functions new `append_chunks()` and `preprend_chunks()` so that the code don't have to manage internal data structures (see https://github.com/davidgohel/flextable/commit/feb0685042a471cdef90e7a483ab0ababb92d742).

**Comment by beansrowning** [comment]
Very elegant! Yes, that is much cleaner.

**Pull request merged**
