### PR TITLE
adds `theme_apa`

### PR DESCRIPTION
**Pull request by rempsyc**
Experimental attempt no 1, ready for future iterations. Not sure if discussion should continue here or in #426.

### CODE REVIEW

**Comment by davidgohel** [comment]
Could you to add an entry in `NEWS.md` and add your name as 'ctb' in `DESCRIPTION`?

**Comment by davidgohel** [comment]
sorry, can you remove the *author* link in pkgdown.yaml ?

**Comment by rempsyc** [comment]
Sorry about that. I have removed it. I initially thought it might be nice to have the author's (you) and other contributors' sites on this page: https://davidgohel.github.io/flextable/authors.html

Like, e.g., for `performance` package: https://easystats.github.io/performance/authors.html

**Comment by davidgohel** [comment]
Thanks!

PS: I will look at this author page. I never really spend time on it to be frank. Once I will populate the page your name will be part of this list

**Comment by rempsyc** [comment]
Just to clarify, the author page is created automatically from the `DESCRIPTION` file by `pkgdown`. Adding authors to `_pkgyml` is not actually adding "authors" to the package, it just adds links to personal websites for contributors, but _only_ if people are listed in the `DESCRIPTION` file already (else it is ignored), i.e., it doesn't add people as authors or contributors by itself.

**Comment by davidgohel** [comment]
OK! dummy me! I'll add back your link to the yaml file

**Comment by davidgohel** [comment]
done

**Pull request merged**
